### ISSUE TITLE
add in-place stub_primitive

### ISSUE THREAD

**Issue by lbartnik** [n-s-f/mockery#10]
if one needs to replace (stub) a primitive in function pkg1::A that is called from pkg2::B neither `stub()` nor `with_mock()` will suffice

one way:

- find the function under test - we want to intercept calls originating from this function; name it X
- unlock environment which function X belongs to
- add a new entry in this unlocked environment named after the primitive we want to mock
- lock the environment

it can be done in pure R as well but requires additional environment:

- take a copy of function X
- put this copy in a new environment whose parent is the env of X
- add the intercept for the primitive in the new env
- unlock binding for original X in its env
- replace X with its copy
- lock binding

the second method is more complex and makes it a bit more difficult to replace the same primitive in subsequent calls or to replace multiple primitives

**Comment by n-s-f** [comment]
@lbartnik 

Would you mind including a quick example test demonstrating what you'd like to do?

From what I understand, the case you're interested in is `yourfunc` calls `pkg2::B` calls `pkg1::A` calls some primative.  If that's the case, I have another question.  Why not just mock out the call to `pkg2::B`? When would it be essential to run that third-party code as part of your tests?
