### ISSUE TITLE
Rename `expect_no_calls` to `expect_called`

### ISSUE THREAD

**Issue by n-s-f** [n-s-f/mockery#15]
@lbartnik 

I believe we originally renamed this to avoid a naming conflict with my function of the same name.

However I think that function is superflous given the mock objects. I am removing it in this pull request: https://github.com/n-s-f/mockery/pull/14

Therefore I'd like to rename the `expect_no_calls` method on the mock objects back to `expect_called`, which I think is much clearer.

Would that interfere with your code?

**Comment by lbartnik** [comment]
Hi Noam,
I believe this change is harmless.

**Comment by n-s-f** [comment]
@lbartnik  

Thanks. I'll rename shortly. That pull request got rid of the other `expect_called` function, so that it is possible to rename without naming conflicts.
