### ISSUE TITLE
Allow user to specify depth of stubbing

### ISSUE THREAD

**Issue by n-s-f** [n-s-f/mockery#17]
At the moment, the stub`stub` function only stubs out the function to be stubbed if it is directly called from the target function.

We should introduce an optional parameter to `stub` that allows the user to specify how deep they want to the stub to be active. E.g. a `stub(some_func, 'other_func', 100, depth=2)` would indicate that `other_func` should be stubbed with something that returns 100 not only if called directly from `some_func`, but also if called by something that `some_func` calls.

**Comment by n-s-f** [comment]
This is currently under development at https://github.com/n-s-f/mockery/tree/depth-nsf

The code currently works as intended. I'll add a few more tests, especially around stubbing things out of what would appear to be locked environments.

**Comment by n-s-f** [comment]
Note to self: add test case for a function that calls the stubbed function directly and also calls a function that then calls the stubbed function.

May need to include parent _names_ and get the parent envs dynamically here https://github.com/n-s-f/mockery/blob/depth-nsf/R/stub.R#L91-L107 instead of storing the envs directly in the _depths_ list, because some of the envs will be swapped out.

**Comment by n-s-f** [comment]
@n-s-f also think about speeding up the stubbing by collapsing the two loops into one and stubbing _as we go_ instead of building up a massive list and then processing it. Will be faster and more space efficient - might be relevant if the default ends up being stubbing all the way down.

**Comment by patr1ckm** [comment]
Just wanted to +1 this, would be really convenient since we can't `with_mock` base functions in `testthat` anymore.

**Comment by n-s-f** [comment]
@patr1ckm Thanks for reminding me of this.

I just updated the code I had written previously; it's available in this branch: https://github.com/n-s-f/mockery/tree/depth

Can you take a look at that code and see if it solves your problem? If so, great. If not, please let me know how it breaks.

I want to clean it up a little before merging into master. I also want to add a few more tests; it's a big chunk of code, only covered by a couple tests.

If you're willing to do a little work on adding unit tests and possibly cleaning up the code that makes this possible, let me know and I can set you in the right direction. That would be helpful in getting this functionality merged.

**Comment by n-s-f** [comment]
Done.

**Comment by patr1ckm** [comment]
Thank you! Sorry I didn't have time to test.

**Comment by n-s-f** [comment]
Sure!

Let me know if you have any issues with it - it's hard to test this deeply, there may be a bug in there somewhere.
